/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramadorRouteImport } from './routes/programador'
import { Route as PlanejadorRouteImport } from './routes/planejador'
import { Route as OperadorRouteImport } from './routes/operador'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KpisRouteImport } from './routes/kpis'
import { Route as EncarregadoRouteImport } from './routes/encarregado'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const ProgramadorRoute = ProgramadorRouteImport.update({
  id: '/programador',
  path: '/programador',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejadorRoute = PlanejadorRouteImport.update({
  id: '/planejador',
  path: '/planejador',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorRoute = OperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisRoute = KpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const EncarregadoRoute = EncarregadoRouteImport.update({
  id: '/encarregado',
  path: '/encarregado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/encarregado': typeof EncarregadoRoute
  '/kpis': typeof KpisRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/mcp': typeof McpRoute
  '/operador': typeof OperadorRoute
  '/planejador': typeof PlanejadorRoute
  '/programador': typeof ProgramadorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/encarregado': typeof EncarregadoRoute
  '/kpis': typeof KpisRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/mcp': typeof McpRoute
  '/operador': typeof OperadorRoute
  '/planejador': typeof PlanejadorRoute
  '/programador': typeof ProgramadorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/encarregado': typeof EncarregadoRoute
  '/kpis': typeof KpisRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/mcp': typeof McpRoute
  '/operador': typeof OperadorRoute
  '/planejador': typeof PlanejadorRoute
  '/programador': typeof ProgramadorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/encarregado'
    | '/kpis'
    | '/login'
    | '/materiais'
    | '/mcp'
    | '/operador'
    | '/planejador'
    | '/programador'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/encarregado'
    | '/kpis'
    | '/login'
    | '/materiais'
    | '/mcp'
    | '/operador'
    | '/planejador'
    | '/programador'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/encarregado'
    | '/kpis'
    | '/login'
    | '/materiais'
    | '/mcp'
    | '/operador'
    | '/planejador'
    | '/programador'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  EncarregadoRoute: typeof EncarregadoRoute
  KpisRoute: typeof KpisRoute
  LoginRoute: typeof LoginRoute
  MateriaisRoute: typeof MateriaisRoute
  McpRoute: typeof McpRoute
  OperadorRoute: typeof OperadorRoute
  PlanejadorRoute: typeof PlanejadorRoute
  ProgramadorRoute: typeof ProgramadorRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programador': {
      id: '/programador'
      path: '/programador'
      fullPath: '/programador'
      preLoaderRoute: typeof ProgramadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejador': {
      id: '/planejador'
      path: '/planejador'
      fullPath: '/planejador'
      preLoaderRoute: typeof PlanejadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador': {
      id: '/operador'
      path: '/operador'
      fullPath: '/operador'
      preLoaderRoute: typeof OperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis': {
      id: '/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof KpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encarregado': {
      id: '/encarregado'
      path: '/encarregado'
      fullPath: '/encarregado'
      preLoaderRoute: typeof EncarregadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  EncarregadoRoute: EncarregadoRoute,
  KpisRoute: KpisRoute,
  LoginRoute: LoginRoute,
  MateriaisRoute: MateriaisRoute,
  McpRoute: McpRoute,
  OperadorRoute: OperadorRoute,
  PlanejadorRoute: PlanejadorRoute,
  ProgramadorRoute: ProgramadorRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
